#ifndef NETWORKDRIVEPROTOCOL
#define NETWORKDRIVEPROTOCOL

typedef enum
{
    MOUNT,
    UNMOUNT,
    CREATE_FILE,
    CLOSE_FILE,
    CLEAN_UP_FILE,
    READ_FILE,
    WRITE_FILE,
    FLUSH_FILE_BUFFERS,
    GET_FILE_INFORMATION,
    FIND_FILES,
    DELETE_FILE,
    DELETE_DIRECTORY,
    MOVE_FILE,
    LOCK_FILE,
    SET_END_OF_FILE,
    SET_ALLOCATION_SIZE,
    SET_FILE_ATTRIBUTES,
    SET_FILE_TIME,
    UNLOCK_FILE,
    GET_FILE_SECURITY,
    SET_FILE_SECURITY,
    GET_VOLUME_INFORMATION,
    ENUMERATE_NAMED_STREAMS

} NetworkDriveMessageType;

#endif // NETWORKDRIVEPROTOCOL

